NF-449 add address audit ref
hmrc/national-import-duty-adjustment-centre-frontend pull request #184
Opened 2021-04-26 12:44 UTC by rorticus0502

2021-04-26 14:43 UTC, njmoorewitchcat requested changes

2021-04-26 14:43 UTC, njmoorewitchcat commented on app/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/controllers/makeclaim/ImporterDetailsController.scala
> +          val requiredExistingAuditableContactDetails: Option[AuditableImporterContactDetails] =
AMBER: I don't think this val adds anything.  Suggested code
```
...
data.updateCreateAnswers { answers =>
          answers.importerContactDetails match {
                case Some(existing) =>
...
```

2021-04-26 14:43 UTC, njmoorewitchcat commented on app/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/controllers/makeclaim/AddressController.scala
> +          val requiredExistingAuditableAddress: Option[AuditableAddress] = answers.claimantAddress
AMBER: I don't think this val adds anything.  Suggested code
```
...
data.updateCreateAnswers { answers =>
          answers.claimantAddress match {
                case Some(existing) =>
...
```

2021-04-26 14:43 UTC, njmoorewitchcat commented on app/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/models/exceptions/MissingAddressException.scala
> +      "This should never happen. You are not allowed onto the manual address form unless you visited ALF first"
OBSERVATION: I was looking for this :grin:

2021-04-26 14:43 UTC, njmoorewitchcat commented on test/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/controllers/makeclaim/ImporterDetailsControllerSpec.scala
> +      withCacheCreateAnswers(emptyAnswers.copy(importerContactDetails = Some(auditableImporterContactDetails)))
AMBER:  It would be better to prefill the cache with an auditableImporterContactDetails that was different than the one we check has been updated.  If I deleted the line controller.onSubmit()(validRequest) then your test would still pass, which means I could modify the underlying controller to accidentally forget to persist, and this would still pass.

2021-04-27 07:34 UTC, rorticus0502 commented on test/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/controllers/makeclaim/ImporterDetailsControllerSpec.scala
> +      withCacheCreateAnswers(emptyAnswers.copy(importerContactDetails = Some(auditableImporterContactDetails)))
Thank you. Good spot. Test for this and for AddressController both updated to seed the answers with a different auditable address.

2021-04-27 07:36 UTC, rorticus0502 commented on app/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/controllers/makeclaim/ImporterDetailsController.scala
> +          val requiredExistingAuditableContactDetails: Option[AuditableImporterContactDetails] =
Agreed, I meant to go back and do that. Thank you

2021-04-27 07:36 UTC, rorticus0502 commented on app/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/controllers/makeclaim/AddressController.scala
> +          val requiredExistingAuditableAddress: Option[AuditableAddress] = answers.claimantAddress
Done

2021-04-27 07:39 UTC, njmoorewitchcat approved these changes

2021-04-27 07:41 UTC, merged