Nf 278 update phonenumber validation
hmrc/national-import-duty-adjustment-centre-frontend pull request #90
Opened 2021-03-03 13:42 UTC by rorticus0502

2021-03-03 14:51 UTC, njmoorewitchcat requested changes

2021-03-03 14:51 UTC, njmoorewitchcat commented on test/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/models/eis/EISCreateCaseRequestValidationSpec.scala
> +            Some(contactDetailsAnswer.copy(telephoneNumber = Some("+44 1234 23534343 (ext 123)")))
CLARIFICATION: Do we need a test (here?) that confirms the EISCreateCaseRequest continues to work with a blank (not set) telephone number in contact details ?

2021-03-03 16:49 UTC, rorticus0502 commented on test/uk/gov/hmrc/nationalimportdutyadjustmentcentrefrontend/models/eis/EISCreateCaseRequestValidationSpec.scala
> +            Some(contactDetailsAnswer.copy(telephoneNumber = Some("+44 1234 23534343 (ext 123)")))
I will add one

2021-03-04 08:28 UTC, njmoorewitchcat approved these changes

2021-03-04 09:27 UTC, merged